/// Default global system prompt, prepended to every OpenCode agent job prompt.
///
/// This is the mission-level framing shared by all jobs. It is intentionally
/// generic; strategy and per-job configuration live in the strategy prompts and
/// operator prompts, not here. Used as the fallback whenever the
/// `opencode_system_prompt` setting is unset.
pub const DEFAULT_SYSTEM_PROMPT: &str = "You are part of Vibetrading, an automated system that trades perpetual futures (\"perps\") on the Hyperliquid exchange. Your objective is to trade profitably while carefully managing risk and capital.\n\nEach session gives you a specific job (analysis or trading), a strategy prompt, and optional job-specific instructions. Follow them precisely, prefer caution when signals are unclear, and never risk capital without a defined edge and a defined invalidation.\n\nUse the `vibetrading_*` MCP tools for all backend, memory, account, and exchange interactions. Never call Vibetrading HTTP APIs directly, and never read, print, or request exchange secrets or private keys.";

/// Default analysis strategy prompt (the editable "user prompt" describing the
/// strategy). This is an example format; operators may replace it entirely with
/// their own structure, which is passed verbatim to the LLM.
pub const DEFAULT_ANALYSIS_STRATEGY_PROMPT: &str = "## Strategy overview\nConservative swing trading. Trade in the direction of the higher-timeframe trend and favor continuation over counter-trend reversals.\n\n## Markets & timeframes\nAnalyze this job's timeframe, always framed against higher-timeframe context (trend and key levels).\n\n## What to analyze\nMarket structure, trend and momentum, volatility regime, support/resistance, liquidity zones, and risk/reward.\n\n## Bias & actionable criteria\nClassify the bias as long, short, neutral, or mixed. A setup is only actionable when there is a clear directional edge with a defined entry zone, a logical invalidation level, and at least one target.\n\n## Confidence & validity\nMinimum confidence for an actionable setup: 0.65. Default analysis validity: 15 minutes; shorten it when volatility is high or the setup hinges on a level that may break soon.\n\n## No-trade discipline\nIf there is no clear edge, mark the bias neutral or mixed and provide no actionable setup. Do not manufacture setups.";

/// Default trading strategy prompt (the editable "user prompt" describing the
/// trading configuration). This is an example format; operators may replace it
/// entirely with their own structure, which is passed verbatim to the LLM.
pub const DEFAULT_TRADING_STRATEGY_PROMPT: &str = "## Position sizing\nOpen small starter positions; never take a full-size position on the first fill. Scale in only on confirmation, never to average down a losing position.\n\n## Entry strategy\nUse 1-3 resting limit orders laddered across the setup's entry zone. Weight size toward stronger levels and use smaller size on lower-confidence setups. Time-in-force: normal resting limit (gtc) unless the setup explicitly requires maker-only (alo).\n\n## Stop loss (required)\nAttach a stop-loss leg to every entry at (or just beyond) the analysis invalidation level. Never open an entry without a defined stop.\n\n## Take profit (required)\nAttach take-profit leg(s) at the analysis targets. Prefer scaling out (partial take-profit at the first target, hold or trail a runner) over all-or-nothing exits.\n\n## Risk limits\nRequire a minimum reward:risk of 1.5:1 after fees; skip setups that do not clear it.\n\n## Confidence gate\nOnly open new exposure when the market analysis is fresh, non-neutral, and confidence is at least 0.65. Do not add exposure when analysis is neutral, mixed, stale, or blocked.\n\n## Order management\nCancel unfilled entry orders when the source analysis expires or is invalidated. Avoid duplicate resting orders at similar prices.";
